# Generated by Django 6.0 on 2025-12-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='summary',
            field=models.TextField(help_text='Short text for the sidebar (approx 1 paragraph)', max_length=500),
        ),
    ]
