# Generated by Django 6.0 on 2025-12-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='principal_message',
            field=models.TextField(blank=True, help_text='Optional: Message from the Principal for major events like Graduation.', null=True),
        ),
    ]
