# Generated by Django 6.0 on 2025-12-22 08:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Write your article here. Use the Image icon to insert photos inside the text.'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(upload_to='news_images/', verbose_name='Featured Image'),
        ),
    ]
