# Generated by Django 6.0 on 2025-12-22 08:31

import ckeditor_uploader.fields
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newsarticle_content_alter_newsarticle_image'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags (e.g. Graduation, Theology)', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='event',
            name='principal_message',
            field=models.TextField(blank=True, help_text='Optional: Message from the Principal', null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Full article content'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='summary',
            field=models.TextField(help_text='Short summary for the sidebar', max_length=500),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category'),
        ),
    ]
