# Generated by Django 6.0 on 2025-12-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_category_newsarticle_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='summary',
            field=models.TextField(blank=True, help_text='Leave blank if you want an Image-Only banner (no text overlay).', max_length=500),
        ),
    ]
