# Generated by Django 6.0 on 2026-01-20 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_newsarticle_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Name of the file (e.g. 'Graduation List PDF')", max_length=200)),
                ('file', models.FileField(upload_to='news_documents/')),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='news.newsarticle')),
            ],
        ),
    ]
