# Generated by Django 6.0 on 2026-01-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_newsdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload a smaller, clean photo for lists and grids. If left blank, the Featured Image will be used.', null=True, upload_to='news_thumbnails/', verbose_name='Thumbnail (Card Image)'),
        ),
    ]
