# Generated by Django 6.0 on 2026-01-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='show_on_slider',
            field=models.BooleanField(default=False, help_text='Check this box if you want this article to appear in the big main slider on the homepage.', verbose_name='Show on Homepage Slider'),
        ),
    ]
