# Generated by Django 6.0 on 2026-03-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_newsarticle_show_on_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_on_slider',
            field=models.BooleanField(default=False, help_text='Check this box if you want this event to appear in the big main slider on the homepage.', verbose_name='Show on Homepage Slider'),
        ),
    ]
