# Generated by Django 6.0 on 2026-09-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_event_show_on_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
