# Generated by Django 6.0 on 2026-09-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_newsarticle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(blank=True, default='temp', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
