# Generated by Django 6.0 on 2026-09-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_event_slug_alter_newsarticle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, default='temp', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(blank=True, default='temp', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
