# Generated by Django 6.0 on 2025-12-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('activity', models.CharField(help_text='e.g. Morning Glory', max_length=200)),
                ('location', models.CharField(default='Campus', help_text='e.g. Main Chapel', max_length=200)),
                ('is_highlighted', models.BooleanField(default=False, help_text='Check this to make the row yellow/gold')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Academic Integrity Policy', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short summary of what is inside')),
                ('file', models.FileField(help_text='Upload the PDF here', upload_to='policies/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
