# Generated by Django 6.0 on 2025-12-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyschedule',
            options={'ordering': ['day_category', 'start_time']},
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='day_category',
            field=models.CharField(choices=[('MONDAY-FRIDAY', 'Monday - Friday'), ('FRIDAY', 'Friday Only'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='MONDAY-FRIDAY', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='period',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM'), ('AM/PM', 'AM/PM')], default='AM', max_length=10),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='activity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='location',
            field=models.CharField(default='Campus', max_length=200),
        ),
    ]
