# Generated by Django 6.0 on 2025-12-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_dailyschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyschedule',
            name='day_category',
            field=models.CharField(choices=[('MONDAY-FRIDAY', 'Monday - Friday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='MONDAY-FRIDAY', max_length=20),
        ),
    ]
