# Generated by Django 6.0 on 2025-12-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dailyschedule_day_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('WHO_WE_ARE', 'Who We Are'), ('STATEMENT', 'Statement of Faith'), ('POLICIES', 'University Policies'), ('SCHEDULE', 'Daily Schedule')], help_text='Select which page this banner belongs to', max_length=50, unique=True)),
                ('image', models.ImageField(help_text='Upload a wide image (approx 1200x400px)', upload_to='page_banners/')),
                ('caption', models.CharField(blank=True, help_text='Optional text to display on the image', max_length=200)),
            ],
        ),
    ]
