# Generated by Django 6.0 on 2025-12-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pagebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Main heading on the slide', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text='Smaller text below heading', max_length=200)),
                ('image', models.ImageField(help_text='Upload a large, high-quality image (1920x800px recommended)', upload_to='home_slider/')),
                ('link', models.CharField(blank=True, help_text='Link for the button (e.g., /admissions/apply/)', max_length=200)),
                ('button_text', models.CharField(blank=True, default='Learn More', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
