# Generated by Django 6.0 on 2026-01-23 13:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g. Journalism Alumnus (2024)', max_length=100)),
                ('photo', models.ImageField(upload_to='testimonials/')),
                ('quote', models.TextField(help_text='Short quote for the card (approx 30 words)')),
                ('full_story', ckeditor_uploader.fields.RichTextUploadingField(help_text='The full detailed story (Notebook view)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
