# Generated by Django 6.0 on 2026-01-26 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_partner_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. Admissions, Students' Welfare", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Order of display on the page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(help_text='e.g. 077... / 070...', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='core.contactdepartment')),
            ],
        ),
    ]
