# Generated by Django 6.0 on 2026-01-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactdepartment_contactperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g. Guild President', max_length=100)),
                ('photo', models.ImageField(upload_to='student_leaders/')),
                ('cabinet_year', models.CharField(choices=[('2026', '2026/2027 Cabinet'), ('2025', '2025/2026 Cabinet'), ('2024', '2024/2025 Cabinet')], default='2026', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('order', models.IntegerField(default=0, help_text='1 for President, 2 for VP, etc.')),
            ],
            options={
                'ordering': ['-cabinet_year', 'order'],
            },
        ),
    ]
