# Generated by Django 6.0 on 2026-01-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_studentleader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagebanner',
            name='page',
            field=models.CharField(choices=[('WHO_WE_ARE', 'Who We Are'), ('STATEMENT', 'Statement of Faith'), ('POLICIES', 'University Policies'), ('SCHEDULE', 'Daily Schedule'), ('GUILD', 'Students Guild')], help_text='Select which page this banner belongs to', max_length=50, unique=True),
        ),
    ]
