# Generated by Django 6.0 on 2026-01-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_pagebanner_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('graduation_year', models.CharField(help_text='Year of Graduation', max_length=4)),
                ('program', models.CharField(help_text='Course studied at ANTS', max_length=200)),
                ('current_job', models.CharField(blank=True, help_text='Current Job Title', max_length=200)),
                ('employer', models.CharField(blank=True, help_text='Company or Church Name', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='alumni_photos/')),
                ('testimonial', models.TextField(blank=True, help_text='A short message about their time at ANTS')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approve for Website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studentleader',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional: Official email (e.g. guild@ants.ac.ug)', max_length=254, null=True),
        ),
    ]
