# Generated by Django 6.0 on 2026-01-30 14:03

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alumnimember_alter_studentleader_email'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Finance Department, University Library', max_length=100)),
                ('slug', models.SlugField(help_text='URL friendly name (e.g. finance-department)', unique=True)),
                ('head_title', models.CharField(default='Head of Department', help_text='e.g. University Bursar, Librarian', max_length=100)),
                ('introduction', ckeditor_uploader.fields.RichTextUploadingField(help_text='Main description (Mandate)')),
                ('duties', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text="Content for 'Duties & Responsibilities' tab")),
                ('staff_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text="Content for 'Staff Members' tab (or list names manually)")),
                ('contact_info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Address, Email, Phone for this specific department')),
                ('head_of_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_services', to='staff.staffmember')),
            ],
        ),
    ]
