# Generated by Django 6.0 on 2026-02-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_servicedepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('preacher', models.CharField(help_text='e.g. Rev. Victor Jung', max_length=100)),
                ('date_preached', models.DateField()),
                ('youtube_link', models.URLField(help_text='Paste the full YouTube link here (e.g., https://www.youtube.com/watch?v=...)')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date_preached'],
            },
        ),
    ]
