# Generated by Django 6.0 on 2026-02-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sermon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='youtube_link',
            field=models.URLField(help_text='Paste the full YouTube link here'),
        ),
    ]
