# Generated by Django 6.0 on 2026-02-03 13:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_sermon_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category_type', models.CharField(choices=[('SCHOLARSHIP', 'Student Scholarships'), ('INFRASTRUCTURE', 'Campus Development'), ('LIBRARY', 'Library & Resources'), ('GENERAL', 'General Operations'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional fundraising target', max_digits=12, null=True)),
                ('icon_class', models.CharField(default='fas fa-heart', help_text='FontAwesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name_plural': 'Donation Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DonationTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, help_text="e.g., 'Ministry Partner since 2015'", max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='testimonials/donors/')),
                ('quote', models.TextField(help_text='The testimonial text')),
                ('donation_relationship', models.CharField(blank=True, help_text="e.g., 'Scholarship Sponsor', 'Monthly Partner'", max_length=255)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on donations page')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Donor Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('donor_phone', models.CharField(blank=True, max_length=20)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide donor name publicly')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('payment_method', models.CharField(choices=[('BANK', 'Bank Transfer'), ('MTN', 'MTN Mobile Money'), ('AIRTEL', 'Airtel Money'), ('CASH', 'Cash'), ('CHECK', 'Cheque'), ('OTHER', 'Other')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='Bank reference or mobile money transaction ID', max_length=100)),
                ('purpose', models.CharField(blank=True, help_text='Specific purpose if different from category', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('donor_message', models.TextField(blank=True, help_text='Message from donor')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('date_confirmed', models.DateField(blank=True, null=True)),
                ('receipt_issued', models.BooleanField(default=False)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.donationcategory')),
            ],
            options={
                'ordering': ['-date_received', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationImpactStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('featured_image', models.ImageField(upload_to='impact_stories/')),
                ('summary', models.TextField(help_text='Brief summary for cards')),
                ('full_story', models.TextField(help_text='Complete story')),
                ('beneficiary_name', models.CharField(blank=True, max_length=200)),
                ('beneficiary_photo', models.ImageField(blank=True, upload_to='impact_stories/beneficiaries/')),
                ('is_published', models.BooleanField(default=True)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.donationcategory')),
            ],
            options={
                'verbose_name_plural': 'Impact Stories',
                'ordering': ['-publish_date'],
            },
        ),
    ]
