# Generated by Django 6.0 on 2026-02-04 12:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_donationcategory_donationtestimonial_donation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Prison Ministry', max_length=200)),
                ('image', models.ImageField(help_text='Cover photo for this ministry', upload_to='outreach/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(help_text='Details about what you do in this ministry')),
                ('location', models.CharField(help_text='e.g. Kigo Prison / Entebbe Hospitals', max_length=200)),
            ],
        ),
    ]
