# Generated by Django 6.0 on 2026-02-04 12:21

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_outreachprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachprogram',
            name='show_on_slider',
            field=models.BooleanField(default=False, verbose_name='Show on Homepage Slider'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a cover photo to display on the Homepage Slider', null=True, upload_to='sermon_thumbnails/'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='show_on_slider',
            field=models.BooleanField(default=False, verbose_name='Show on Homepage Slider'),
        ),
        migrations.AlterField(
            model_name='outreachprogram',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='outreachprogram',
            name='image',
            field=models.ImageField(upload_to='outreach/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='outreachprogram',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='outreachprogram',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='OutreachImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='outreach_gallery/')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.outreachprogram')),
            ],
        ),
    ]
