# Generated by Django 6.0 on 2026-03-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_outreachprogram_show_on_slider_sermon_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200)),
                ('tuition_per_semester', models.DecimalField(decimal_places=0, max_digits=12)),
                ('functional_fees', models.DecimalField(decimal_places=0, max_digits=12)),
                ('academic_year', models.CharField(default='2026', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
