# Generated by Django 6.0 on 2026-03-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_feestructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, help_text='e.g. 6:00 AM – 11:00 PM', max_length=100)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome class e.g. fas fa-cross', max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured event timeline')),
                ('show_on_slider', models.BooleanField(default=False, help_text='Feature on homepage slider')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
