# Generated by Django 6.0 on 2026-03-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_chapelevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapelevent',
            name='image',
            field=models.ImageField(blank=True, help_text='Banner image for slider and events page', null=True, upload_to='chapel_events/'),
        ),
    ]
