# Generated by Django 6.0 on 2026-03-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_chapelevent_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapelAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(default='The Heart of Campus', max_length=100)),
                ('section_title', models.CharField(default='A Place of Spiritual Formation', max_length=200)),
                ('scripture_text', models.TextField(help_text='The scripture quote e.g. Acts 2:42')),
                ('scripture_reference', models.CharField(help_text='e.g. Acts 2:42', max_length=100)),
                ('paragraph_1', models.TextField()),
                ('paragraph_2', models.TextField(blank=True)),
                ('chapel_image', models.ImageField(blank=True, null=True, upload_to='chapel/')),
                ('image_caption', models.CharField(default='ANTS Chapel', max_length=200)),
                ('image_subcaption', models.CharField(default='Completed 2003 · Kisubi, Uganda', max_length=200)),
            ],
            options={
                'verbose_name': 'Chapel About Section',
            },
        ),
    ]
