# Generated by Django 6.0 on 2026-03-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_chapelabout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapelPreacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('chapel', 'Chapel Service (Mon-Fri)'), ('friday_prayer', 'Friday Evening Prayer'), ('sunday_worship', 'Sunday Worship Service')], max_length=20)),
                ('day', models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sun', 'Sunday')], max_length=3)),
                ('preacher_name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, help_text='e.g. Presider, Preacher, Worship Leader', max_length=100)),
                ('week_of', models.DateField(help_text='Monday of the week this applies to')),
            ],
            options={
                'ordering': ['week_of', 'service_type', 'day'],
            },
        ),
        migrations.DeleteModel(
            name='ChapelAbout',
        ),
    ]
