# Generated by Django 6.0 on 2026-04-16 09:05

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_chapelpreacher_delete_chapelabout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Full body of the notice.')),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('admissions', 'Admissions'), ('chapel', 'Chapel'), ('finance', 'Finance'), ('staff', 'Staff'), ('general', 'General')], default='general', max_length=30)),
                ('target_audience', models.CharField(choices=[('all', 'Everyone'), ('students', 'Students'), ('staff', 'Staff'), ('public', 'Public')], default='all', help_text='Who this notice is directed at.', max_length=20)),
                ('attachment', models.FileField(blank=True, help_text='Optional PDF or document.', null=True, upload_to='notice_attachments/')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from the website.')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned notices always appear at the top.')),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-is_pinned', '-date_posted'],
            },
        ),
    ]
