# Generated by Django 6.0 on 2026-06-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Bold headline e.g. 'Admissions Now Open'", max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Smaller line below the headline', max_length=300)),
                ('body_text', models.TextField(blank=True, help_text='Short paragraph (1–2 sentences)')),
                ('theme', models.CharField(choices=[('admissions', 'Admissions'), ('event', 'Event'), ('notice', 'General Notice'), ('graduation', 'Graduation')], default='admissions', max_length=20)),
                ('cta_text', models.CharField(default='Apply Now', help_text='Button label', max_length=50)),
                ('cta_url', models.URLField(default='https://admissions.ants.ac.ug', help_text='Button link')),
                ('footer_note', models.CharField(blank=True, help_text="Gold bar text e.g. 'Deadline: 30th June 2026'", max_length=200)),
                ('is_active', models.BooleanField(default=False, help_text='Check to show popup on every page. Uncheck to hide it.')),
            ],
            options={
                'verbose_name': 'Popup Banner',
                'verbose_name_plural': 'Popup Banners',
            },
        ),
    ]
