# Generated by Django 6.0 on 2026-06-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_popupbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupbanner',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo — shown on the left side of the popup (portrait/square works best, e.g. a graduate photo)', null=True, upload_to='popup_banners/'),
        ),
    ]
