# Generated by Django 6.0 on 2026-06-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_popupbanner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimatedSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Admissions Open', help_text="Small pill label e.g. 'Admissions Open'", max_length=60)),
                ('headline', models.CharField(help_text="First line of big heading e.g. 'Start Your'", max_length=100)),
                ('headline_accent', models.CharField(help_text="Gold second line e.g. 'Ministry Journey.'", max_length=100)),
                ('subtext', models.CharField(blank=True, help_text="Short line below heading e.g. 'August 2026/2027 Intake — Applications open.'", max_length=220)),
                ('theme', models.CharField(choices=[('admissions', 'Admissions'), ('graduation', 'Graduation'), ('event', 'Event'), ('general', 'General')], default='admissions', max_length=20)),
                ('chip1_label', models.CharField(blank=True, default='Intake', help_text='e.g. Intake', max_length=30)),
                ('chip1_value', models.CharField(blank=True, default='Aug 2026/27', max_length=50)),
                ('chip2_label', models.CharField(blank=True, default='Deadline', help_text='e.g. Deadline', max_length=30)),
                ('chip2_value', models.CharField(blank=True, default='30th June 2026', max_length=50)),
                ('chip3_label', models.CharField(blank=True, default='Mode', help_text='e.g. Mode', max_length=30)),
                ('chip3_value', models.CharField(blank=True, default='Full / Part-time', max_length=50)),
                ('cta_text', models.CharField(default='Apply Now', max_length=50)),
                ('cta_url', models.URLField(default='https://admissions.ants.ac.ug')),
                ('ghost_text', models.CharField(blank=True, default='View Programmes', help_text='Secondary link label (leave blank to hide)', max_length=50)),
                ('ghost_url', models.CharField(blank=True, default='/academics/programmes/', max_length=200)),
                ('stat1_num', models.CharField(blank=True, default='30+', max_length=20)),
                ('stat1_label', models.CharField(blank=True, default='Years of excellence', max_length=50)),
                ('stat2_num', models.CharField(blank=True, default='15+', max_length=20)),
                ('stat2_label', models.CharField(blank=True, default='Degree programmes', max_length=50)),
                ('stat3_num', models.CharField(blank=True, default='June 30', max_length=20)),
                ('stat3_label', models.CharField(blank=True, default='Application deadline', max_length=50)),
                ('deadline_text', models.CharField(blank=True, default='Application Deadline — 30th June 2026', help_text='Gold bar at bottom of slide', max_length=120)),
                ('image', models.ImageField(help_text='Background photo — 1000×559px recommended', upload_to='animated_slides/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower = appears first in slider')),
                ('is_active', models.BooleanField(default=False, help_text='Check to include in homepage slider')),
            ],
            options={
                'verbose_name': 'Animated Slide',
                'verbose_name_plural': 'Animated Slides',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='popupbanner',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo shown on the left side of the popup', null=True, upload_to='popup_banners/'),
        ),
    ]
