# Generated by Django 6.0 on 2025-12-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated part of the URL (e.g. prof-joy-kwesiga)', unique=True)),
                ('role', models.CharField(help_text='e.g. Dean of Students', max_length=100)),
                ('category', models.CharField(choices=[('PRINCIPAL', 'The Principal'), ('MANAGEMENT', 'Management & Admin'), ('OFFICE', 'Office Staff'), ('ACADEMIC', 'Academic Staff'), ('SUPPORT', 'Support Staff')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Main biography text')),
                ('cv', models.FileField(blank=True, help_text='Upload PDF Resume/CV', null=True, upload_to='staff_cvs/')),
                ('qualifications', models.TextField(blank=True, help_text='List qualifications here')),
                ('research_interests', models.TextField(blank=True, help_text='Areas of research')),
                ('publications', models.TextField(blank=True, help_text='List of publications')),
                ('projects', models.TextField(blank=True, help_text='Current or past projects')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
