# Generated by Django 6.0 on 2025-12-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g. Dean of Students', max_length=100)),
                ('category', models.CharField(choices=[('PRINCIPAL', 'The Principal'), ('MANAGEMENT', 'Management & Admin'), ('ACADEMIC', 'Academic Staff'), ('SUPPORT', 'Support Staff')], max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first (e.g. Principal = 1)')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
