# Generated by Django 6.0 on 2026-04-23 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffmember_service_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_theme', models.CharField(choices=[('default', 'Professional Blue (Default)'), ('dark', 'Midnight Dark'), ('light', 'Clean Light'), ('accent', 'University Gold')], default='default', max_length=20)),
                ('staff_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffmember')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
