# Generated by Django 6.0 on 2025-12-12 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField(help_text='YYYY-MM-DD')),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated')], max_length=20)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('tribe', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, verbose_name='Telephone No.')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('permanent_address', models.TextField(verbose_name='Permanent Address')),
                ('next_of_kin_name', models.CharField(max_length=200, verbose_name='Next of Kin Name')),
                ('next_of_kin_contact', models.CharField(max_length=100, verbose_name='Next of Kin Phone')),
                ('next_of_kin_relationship', models.CharField(max_length=50, verbose_name='Relationship (e.g. Father/Spouse)')),
                ('attending_church', models.CharField(max_length=200, verbose_name='Attending Church')),
                ('church_location', models.CharField(max_length=200, verbose_name='Location of Church')),
                ('church_title', models.CharField(blank=True, max_length=100, verbose_name='Your Title (e.g. Pastor/Elder)')),
                ('baptism_date', models.CharField(blank=True, max_length=50, verbose_name='Time of Baptism')),
                ('senior_pastor', models.CharField(max_length=200, verbose_name="Senior Pastor's Name")),
                ('pastor_contact', models.CharField(max_length=100, verbose_name="Pastor's Contact")),
                ('education_history', models.TextField(help_text='List your previous schools: Institute, Period, and Certificate/Degree obtained.', verbose_name='Educational Background')),
                ('finance_method', models.CharField(choices=[('Private', 'Private Funds'), ('Scholarship', 'Scholarship from ANTS'), ('Sponsor', 'Sponsorship through Sponsor')], max_length=20, verbose_name='How do you intend to fund your studies?')),
                ('sponsor_name', models.CharField(blank=True, max_length=200, verbose_name='Sponsor Name (if applicable)')),
                ('passport_photo', models.ImageField(upload_to='applications/photos/', verbose_name='Passport Photo')),
                ('academic_documents', models.FileField(upload_to='applications/docs/', verbose_name='Academic Transcripts/Certificates (PDF)')),
                ('recommendation_letter', models.FileField(blank=True, null=True, upload_to='applications/docs/', verbose_name='Recommendation Letter (Optional)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('program_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.program', verbose_name='Program Applied For')),
            ],
        ),
    ]
