# Generated by Django 6.0 on 2026-04-30 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='academic_documents',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='baptism_date',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='church_location',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='education_history',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='next_of_kin_contact',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='next_of_kin_name',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='next_of_kin_relationship',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='recommendation_letter',
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='academic_docs_file',
            field=models.FileField(default='', upload_to='applications/docs/', verbose_name='Upload All Documents (One PDF)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='academic_prizes',
            field=models.TextField(blank=True, default='', verbose_name='Academic Prizes and Distinctions'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='denomination',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Denomination'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='english_instruction',
            field=models.BooleanField(default=True, verbose_name='Was English the language of instruction?'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='family_contact_1',
            field=models.CharField(default='None', max_length=100, verbose_name='Contact of Family (1)'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='family_contact_2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Contact of Family (2)'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='future_plan',
            field=models.TextField(default='Ministry', verbose_name='Future plan after studying at ANTS'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='has_certificates',
            field=models.BooleanField(default=False, verbose_name='Certificates Included'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='has_recommendation',
            field=models.BooleanField(default=False, verbose_name='Recommendation Letter Included'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='has_testimony',
            field=models.BooleanField(default=False, verbose_name='Personal Testimony Included'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='has_transcripts',
            field=models.BooleanField(default=False, verbose_name='Transcripts Included'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='is_first_study',
            field=models.BooleanField(default=True, verbose_name='Is this your first study?'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='location_of_church',
            field=models.CharField(default='Not Specified', max_length=200, verbose_name='Location of Church'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='official_comment',
            field=models.TextField(blank=True, default='', verbose_name='Official Comment (Official Use Only)'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='person_known_to_ants',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name of person known to ANTS'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='purpose_of_study',
            field=models.TextField(default='Theological training', verbose_name='Purpose of studying at ANTS'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='source_details',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Specify Source details'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='source_of_info',
            field=models.CharField(choices=[('Website', 'Website'), ('Social Media', 'Social Media'), ('Brochure', 'Brochure/Prospectus'), ('Student', 'Student of ANTS'), ('Professor', 'Professor of ANTS'), ('Missionary', 'Missionary'), ('Pastor', 'Pastor of my church'), ('Poster', 'Poster'), ('Advertisement', 'Advertisement'), ('Other', 'Other')], default='Website', max_length=50),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='testimony_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/docs/', verbose_name='Personal Testimony File'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='time_of_baptism',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Time of Baptism'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='church_title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Title (e.g. Pastor/Elder)'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='finance_method',
            field=models.CharField(choices=[('Private', 'Private Funds'), ('Scholarship', 'Scholarship from ANTS'), ('Sponsor', 'Sponsorship through Sponsor')], default='Private', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated'), ('Widowed', 'Widowed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='nationality',
            field=models.CharField(default='Ugandan', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='place_of_birth',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='sponsor_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Sponsor Name'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='tribe',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='EducationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=100)),
                ('award', models.CharField(max_length=255, verbose_name='Certificate/Diploma/Degree')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to='admissions.studentapplication')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=255)),
                ('post_held', models.CharField(max_length=255, verbose_name='Post Held / Main Duties')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_entries', to='admissions.studentapplication')),
            ],
        ),
    ]
