# Generated by Django 6.0 on 2026-05-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_remove_studentapplication_academic_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='recommendation_letter',
            field=models.FileField(blank=True, null=True, upload_to='applications/docs/'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='academic_docs_file',
            field=models.FileField(upload_to='applications/docs/', verbose_name='Academic Documents (PDF)'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='has_certificates',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='has_recommendation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='has_testimony',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='has_transcripts',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='testimony_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/docs/', verbose_name='Personal Testimony'),
        ),
    ]
