# Generated by Django 6.0 on 2026-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_studentapplication_recommendation_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='source_details',
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='future_plan',
            field=models.TextField(default='', verbose_name='Future plan after studying at ANTS'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='purpose_of_study',
            field=models.TextField(default='', verbose_name='Purpose of studying at ANTS'),
        ),
    ]
