# Generated by Django 6.0 on 2026-05-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_remove_studentapplication_source_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='family_contact_1',
            field=models.CharField(default='', max_length=100, verbose_name='Contact of Family (1)'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='location_of_church',
            field=models.CharField(default='', max_length=200, verbose_name='Location of Church'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='place_of_birth',
            field=models.CharField(default='', max_length=100),
        ),
    ]
