# Generated by Django 6.0 on 2026-05-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_alter_studentapplication_family_contact_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='family_members_count',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Number of family members'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='source_details',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Specify Source details'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='academic_docs_file',
            field=models.FileField(default='', upload_to='applications/docs/', verbose_name='Academic Documents (PDF)'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='passport_photo',
            field=models.ImageField(default='', upload_to='applications/photos/', verbose_name='Passport Photo'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='recommendation_letter',
            field=models.FileField(blank=True, default='', null=True, upload_to='applications/docs/'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='testimony_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='applications/docs/', verbose_name='Personal Testimony'),
        ),
    ]
