# Generated by Django 6.0 on 2026-05-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_studentapplication_family_members_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='family_members_count',
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='num_brother',
            field=models.PositiveIntegerField(default=0, verbose_name='Brother'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='num_daughter',
            field=models.PositiveIntegerField(default=0, verbose_name='Daughter'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='num_father',
            field=models.PositiveIntegerField(default=0, verbose_name='Father'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='num_husband',
            field=models.PositiveIntegerField(default=0, verbose_name='Husband'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='num_mother',
            field=models.PositiveIntegerField(default=0, verbose_name='Mother'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='num_others',
            field=models.PositiveIntegerField(default=0, verbose_name='Others'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='num_sister',
            field=models.PositiveIntegerField(default=0, verbose_name='Sister'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='num_son',
            field=models.PositiveIntegerField(default=0, verbose_name='Son'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='num_wife',
            field=models.PositiveIntegerField(default=0, verbose_name='Wife'),
        ),
    ]
