# Generated by Django 6.0 on 2025-12-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL name (e.g. bachelor-of-theology)', unique=True)),
                ('category', models.CharField(choices=[('BACHELOR', 'Bachelor Programs'), ('DIPLOMA', 'Diploma Programs'), ('CERTIFICATE', 'Certificate Programs'), ('SHORT', 'Short Courses')], max_length=20)),
                ('duration', models.CharField(help_text='e.g. 3 Years', max_length=100)),
                ('study_mode', models.CharField(default='Full-time / Weekend', help_text='e.g. Full-time, Online, Holiday', max_length=100)),
                ('summary', models.TextField(help_text='Short description for the list page (2-3 sentences)')),
                ('overview', models.TextField(help_text='Full detailed description of the course')),
                ('requirements', models.TextField(help_text='Admission requirements (e.g. 2 Principal Passes)')),
                ('image', models.ImageField(blank=True, help_text='Cover image for the course', null=True, upload_to='program_images/')),
                ('brochure', models.FileField(blank=True, help_text='Upload PDF Fee Structure or Brochure', null=True, upload_to='program_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
