# Generated by Django 6.0 on 2026-01-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_featured_in_menu',
            field=models.BooleanField(default=False, help_text='Check this box if you want this specific course to appear directly in the Main Menu dropdown (e.g. ESL, PTC)'),
        ),
    ]
