# Generated by Django 6.0 on 2026-01-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_program_is_featured_in_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(blank=True, choices=[('BACHELOR', 'Bachelor Programs'), ('DIPLOMA', 'Diploma Programs'), ('CERTIFICATE', 'Certificate Programs'), ('SHORT', 'Short Courses')], max_length=20, null=True),
        ),
    ]
