# Generated by Django 6.0 on 2026-02-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_program_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Upload a wide image (1920x600) for the top background. If empty, a default blue banner is used.', null=True, upload_to='program_banners/', verbose_name='Top Header Banner (Wide)'),
        ),
    ]
