# Generated by Django 6.0 on 2026-03-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_program_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='what_you_will_learn',
            field=models.TextField(blank=True, help_text='Describe what students will learn in this program.', null=True),
        ),
    ]
