# Generated by Django 6.0 on 2026-03-09 10:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_program_what_you_will_learn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='overview',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Full detailed description of the course'),
        ),
    ]
